name: First Workflow

on:
  workflow_dispatch    # Manually trigger the action
  # push:
  #   branches: [ main ]  # Trigger the action on push to main branch

jobs:
  basic:
    runs-on: ubuntu-latest

    steps:
      - name: Print greeting
        run: echo "Hello World"
  
  exit:
    runs-on: ubuntu-latest

    steps:
      - name: Print Goodbye
        run: |
          echo "Done, Bye!"
          echo "See you again"
      
      - name: Today's date
        run: date
    
    info:
      runs-on: ubuntu-latest

      steps:
        - name: Get info
          run: echo "{{ toJSON($github)}}"