name: Test Project

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  initial:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Cache dependencies
        working-directory: ./test-project
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        working-directory: ./test-project
        run: npm ci

      - name: Lint code
        working-directory: ./test-project
        run: npm run lint

      - name: Test code
        working-directory: ./test-project
        run: npm run test

  build:
    needs: initial
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Cache dependencies
        working-directory: ./test-project
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        working-directory: ./test-project
        run: npm ci

      - name: Build code
        working-directory: ./test-project
        run: npm run build

      - name: Output file name
        working-directory: ./test-project
        id: publish
        run: find public/*.svg -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # - name: Download artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: dist-files
      # - name: List artifacts
      #   run: ls
      - name: Output value
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: Deploy code
        run: echo "Deploying..."
